### ISSUE TITLE
Specific calendar for each user

### ISSUE THREAD

**Issue by pepe95270** [carlescliment/calendar-bundle#36]
Hi all,
It's more a question than an issue but anyway...
Is it possible to associate a calendar to a user, so each user could manage it's own calendar ?

Thanks for the great bundle :)

**Comment by carlescliment** [comment]
Yes, it is possible. First you need to store the user id in your `Event` entity. Write your own `EventRepository` to customize the queries and filter only the current user. You can use Aggregation to set the current user.

```
use BladeTester\CalendarBundle\Repository

class EventRepository implements EventRepositoryInterface
{
    private $user;

    public function setUser(User $user)
    {
        $this->user = $user;
    }

    // Your implementation for the interface methods goes here
}
```

Then declare your repository as a service for the bundle:

```
    blade_tester_calendar.repository.event:
        class: Vet\CalendarBundle\Repository\EventRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [VetCalendarBundle:Event]
        calls:
          - [setUser, [@current_user]]
```

This code is an approximation, you may need to find out how to inject the current user.

Hope it helps you.
